data = {
  Griddies: {
    textS: 50,
    characters: [
      [
        {
          letter: "P",
          angle: 0,
          threshold: 0.3,
        },
        {
          letter: "R",
          angle: 0,
          threshold: 0.3,
        },
      ],
    ],
    noChar: 2,
    startX: 0.25,
    startY: 0.25,
    fill: true,
    backgroundColor: "#000000",
    palette: ["#c20114", "#6d7275", "#c7d6d5", "#ecebf3"],
    stroke: false,
    strokeWeight: 2,
    alpha: 200,
    designer: "Manfred Klein",
    font: "Griddies-p93d.ttf",
    link: "https://www.fontspace.com/griddies-font-f8177",
    useHSB: false,
    overlap: false,
    startMidpoint: true,
  },
  Squiggles: {
    textS: 50,
    noChar: 1,
    startX: 0.5,
    startY: 0.5,
    fill: false,
    backgroundColor: "#fdfff7",
    palette: ["#0fa3b1", "#d9e5d6", "#eddea4", "#f7a072", "#ff9b42"],
    stroke: true,
    strokeWeight: 2,
    alpha: 120,
    characters: [
      {
        letter: "Z",
        angle: 180,
        threshold: 0.2,
      },
    ],
    designer: "Su Lucas",
    font: "Slsquiggles-RJ96.ttf",
    link: "https://www.fontspace.com/sl-squiggles-font-f6723",
    useHSB: false,
    overlap: true,
    startMidpoint: true,
  },
  Corners: {
    characters: [
      {
        letter: "W",
        angle: 180,
        threshold: 0.2,
      },
      {
        letter: "N",
        angle: 90,
        threshold: 0.2,
      },
    ],
    textS: 30,
    startX: 0.5,
    startY: 0.5,
    fill: false,
    backgroundColor: "#fdfff7",
    palette: ["#064789", "#427aa1", "#679436", "#a5be00", "#fdfff7"],
    stroke: true,
    strokeWeight: 2,
    alpha: 100,
    noChar: 1,
    designer: "Sassy Graphics",
    font: "CornersAndBorders-7XeE.ttf",
    link: "https://www.fontspace.com/corners-and-borders-font-f12948",
    useHSB: false,
    overlap: true,
    startMidpoint: true,
  },
  KR_corner: {
    characters: [
      [
        {
          letter: "B",
          angle: 90,
          threshold: 0.3,
        },
        {
          letter: "A",
          angle: 180,
          threshold: 0.3,
        },
      ],
      [
        {
          letter: "J",
          angle: 90,
          threshold: 0.3,
        },
        {
          letter: "I",
          angle: 180,
          threshold: 0.3,
        },
      ],
      [
        {
          letter: "N",
          angle: 90,
          threshold: 0.3,
        },
        {
          letter: "M",
          angle: 180,
          threshold: 0.3,
        },
      ],
    ],
    textS: 50,
    startX: 0.5,
    startY: 0.5,
    fill: false,
    backgroundColor: "#fff",
    palette: ["#28656c", "#968e88", "#82b498", "#0e273c"],
    stroke: true,
    strokeWeight: 1,
    alpha: 100,
    noChar: 1,
    designer: "Kat's Fun Fonts",
    font: "KrCorners-BGzB.ttf",
    link: "https://www.fontspace.com/kr-corners-font-f6540",
    useHSB: false,
    overlap: true,
    startMidpoint: true,
  },
  Deco_dings: {
    characters: [
      {
        letter: "E",
        angle: 180,
        threshold: 0.5,
      },
    ],
    textS: 50,
    startX: 0.5,
    startY: 0.5,
    backgroundColor: "#000",
    palette: ["#904c77", "#e49ab0", "#a3c3d9", "#26547c", "#957d95", "#000"],
    fill: false,
    stroke: true,
    strokeWeight: 3,
    alpha: 120,
    noChar: 1,
    designer: "Lady Timeless",
    font: "CathysArtDecoDingsLt-5yMx.ttf",
    link: "https://www.fontspace.com/cathys-art-deco-dings-lt-font-f35",
    useHSB: false,
    overlap: true,
    startMidpoint: true,
  },
  HDGEMS7: {
    characters: [
      {
        letter: "A",
        angle: 90,
        threshold: 0.2,
      },
      {
        letter: "E",
        angle: 180,
        threshold: 0.5,
      },
      {
        letter: "L",
        angle: 90,
        threshold: 0.5,
      },
    ],
    textS: 50,
    startX: 0.5,
    startY: 0.5,
    fill: false,
    backgroundColor: "#000",
    palette: ["#904c77", "#e49ab0", "#a3c3d9", "#26547c", "#957d95"],
    stroke: true,
    strokeWeight: 2,
    alpha: 125,
    noChar: 1,
    designer: "HDGEMS7",
    font: "Hdgems7-XXM9.ttf",
    link: "https://www.fontspace.com/hdgems7-font-f5946",
    useHSB: false,
    overlap: false,
    startMidpoint: true,
  },
  Designs_Galore: {
    characters: [
      {
        letter: "T",
        angle: 90,
        threshold: 0.5,
      },
      {
        letter: "M",
        angle: 90,
        threshold: 0.5,
      },
    ],
    textS: 50,
    startX: 0.5,
    startY: 0.5,
    fill: false,
    backgroundColor: "#fff",
    palette: ["#0c4767", "#566E3D", "#B9A44C", "#FE9920", "#FA7921"],
    stroke: true,
    strokeWeight: 1,
    alpha: 125,
    noChar: 1,
    designer: "Cyberbuny Creations",
    font: "DesignsGalore4-l9A0.ttf",
    link: "https://www.fontspace.com/designs-galore-font-f5190",
    useHSB: false,
    overlap: true,
    startMidpoint: false,
  },
};
